import { Inter } from "next/font/google";
import QueryProvider from "@/components/providers/QueryProvider";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import ThemeProvider from "@/context/ThemeContext";
import TokenProvider from "@/context/TokenContext";
import { cookies } from "next/headers";
import AuthProvider from "@/context/AuthContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({ children }) {
  const cookieStore = await cookies();
  const authToken = cookieStore.get("authToken")?.value;

  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <TokenProvider initialToken={authToken}>
          <ThemeProvider>
            <QueryProvider>
              <AuthProvider authToken={authToken}>
                <Toaster />
                <main>{children}</main>
              </AuthProvider>
            </QueryProvider>
          </ThemeProvider>
        </TokenProvider>
      </body>
    </html>
  );
}

const themeScript = `
   (function() {
      let theme = localStorage.getItem("theme") || "dark";
      document.documentElement.classList.add(theme);
    })();
`;
