import { Inter } from "next/font/google";
import QueryProvider from "@/components/providers/QueryProvider";
import { Toaster } from "@/components/ui/toaster";
import "./globals.css";
import ThemeProvider from "@/context/ThemeContext";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default async function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
      </head>
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <ThemeProvider>
          <QueryProvider>
            <Toaster />
            <main>{children}</main>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

const themeScript = `
   (function() {
      let theme = localStorage.getItem("theme") || "dark";
      document.documentElement.classList.add(theme);
    })();
`;
